### ISSUE TITLE
missing file when server starts

### ISSUE THREAD

**Issue by sabr-p** [schahriar/Galleon#2]
after starting the galleon server, this shows up: 

  sudo authbind --deep galleon start 
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
TASK INITIATED: STARTING A NEW GALLEON INSTANCE ...
[PM2][ERROR] script not found : /home/sabrp/galleon.js

after creating the file with the code from github, it starts properly. maybe an ENV_VAR is missing, or copying the file was forgotten in the build?

**Comment by schahriar** [comment]
I've fixed the bug and published **v0.2.4** to npm. You can try reinstalling Galleon or updating it through npm by typing **npm update -g galleon**. I've also deprecated all versions below 0.2.4.

**Comment by sabr-p** [comment]
nice, thanks for the quick fix :)

to anybody curious, the whole bunch of commits is here:
https://github.com/schahriar/Galleon/compare/f48ad75...d2f3060
